/**
 * 展示标签表（#11）：节中文名 + 高频字段中文名 + oneOf 分支中文名。
 *
 * schema 自带 title/description（节级 title + 字段级 description 作为输入
 * 提示），字段级中文标签缺失时回退字段名本身——字典只收高频字段改善
 * 可读性，未收字段不阻塞任何功能。
 */

/** 内容节中文名（节导航与节标题）。 */
export const SECTION_LABELS: Readonly<Record<string, string>> = {
  skills: '技艺',
  items: '物品',
  recipes: '配方',
  enemies: '敌人',
  gearDrops: '异宝掉落',
  elements: '系别',
  rarities: '稀有度',
  affixPool: '词条池',
  combatText: '战斗文案',
  texts: '界面文案',
  shop: '坊市',
  config: '配置',
  rebirth: '转生',
  dungeons: '秘境',
  bosses: 'Boss',
  achievements: '成就',
};

/** 高频字段中文名（miss 时回退字段名）。 */
const FIELD_LABELS: Readonly<Record<string, string>> = {
  id: '标识',
  name: '名称',
  icon: '图标',
  description: '描述',
  type: '类型',
  sell: '出售价',
  level: '层数',
  kind: '动词风格',
  element: '系别',
  affinities: '系别亲和',
  hp: '血量',
  atk: '攻击',
  def: '防御',
  attackInterval: '攻击间隔',
  exp: '经验',
  gold: '灵石掉落',
  drops: '掉落表',
  min: '最小',
  max: '最大',
  chance: '概率',
  weight: '权重',
  slot: '槽位',
  bonuses: '属性加成',
  effect: '持续效果',
  heal: '即时恢复',
  percent: '比例',
  duration: '时长',
  multipliers: '倍率',
  crit: '暴击',
  floorRange: '掉落层段',
  tierRange: '纹阶区间',
  preferredTags: '偏好标签',
  inherentModifiers: '胚纹',
  tiers: '三阶表',
  feature: '特色铭纹',
  tags: '标签',
  stat: '属性键',
  zone: '聚合区',
  value: '数值',
  condition: '条件',
  moveId: '招式键',
  primitive: '机制原语',
  signature: '机制签名',
  prototypeKey: '原型键',
  prototypeParent: '继承自',
  skill: '所属技艺',
  unlockLevel: '解锁层数',
  output: '产出',
  materials: '材料',
  successRate: '成功率',
  interval: '耗时',
  byproduct: '副产出',
  price: '售价',
  count: '数量',
  item: '物品',
  floors: '总层数',
  entry: '进入条件',
  key: '钥匙物品',
  layers: '层表',
  mult: '属性修正',
  enemies: '敌人',
  rewards: '层奖励',
  recommendedPower: '推荐战力',
  threshold: '血量阈值',
  phases: '阶段',
  mods: '属性修正',
  moveKey: '变招',
  narration: '转场叙事',
  summons: '召唤脚本',
  moves: '招式注册',
  verbs: '动词池',
  openings: '开战白',
  critIntro: '暴击引',
  cons: '普攻连',
  fatal: '致命一击',
  templates: '句式模板',
  notes: '战报批注',
  summary: '战报小结',
  compare: '对照句',
  elementFlavor: '系别风味',
  hidden: '隐藏',
  reward: '奖励',
  target: '阈值目标',
  op: '比较方向',
  reset: '重置清单',
  keep: '保留清单',
  formula: '兵解公式',
  talents: '天赋树',
  realms: '境界词表',
  unlocks: '解锁表',
  requires: '前置节点',
  effects: '效果',
  slots: '槽位表',
  combat: '战斗参数',
  progression: '成长参数',
  affix: '词条参数',
  crafting: '炼制参数',
  gear: '装备参数',
  shardItem: '器屑物品',
  reforgeCost: '重铸费用',
  tagWeightPerMatch: '标签加权',
  basicName: '基础动作名',
  reject: '拒绝文案',
  shell: '壳层文案',
  pool: '异宝池',
  showcase: '展示色',
  smelt: '熔炼产出',
  scale: '成长系数',
  v: '动词短语',
  limbs: '部位',
  version: '包版本',
  attacks: '普攻',
  crits: '暴击',
  counters: '克制',
  resists: '抗性',
  light: '轻创',
  mid: '中创',
  heavy: '重创',
  deadly: '致命',
};

/** 字段展示名：字典优先，miss 回退字段名。 */
export function fieldLabel(field: string): string {
  return FIELD_LABELS[field] ?? field;
}

/** oneOf 分支判别值 → 中文形态名（item 五形态）。 */
export const BRANCH_LABELS: Readonly<Record<string, string>> = {
  mat: '材料',
  consumable: '消耗品',
  equip: '装备',
  blank: '器胚',
  inscription: '铭纹',
};
