/**
 * 跨测试共享的 texts.shell 夹具（#26）。
 *
 * shell 入 schema required 后，一切"最小合法包"夹具都需要合法 shell 节；
 * 这里提供一份键全集、短文案的完整 shell，包侧用例在其深拷贝上做单点
 * 破坏断言（required/pattern/percent 等负路径）。值刻意极短——语义正确性
 * 由修仙包装配用例（xiuxianPack.test.ts）承载，本夹具只证形态合法。
 */
export function shellFixture(): Record<string, unknown> {
  return {
    brand: { sigil: '道', name: '问道长生', locale: 'zh-CN', bootError: '中止：{message}' },
    topbar: {
      statsTitle: '属性',
      statsSigil: '斗',
      goldTitle: '灵石',
      goldSigil: '石',
      hpTitle: '气血',
      hpSigil: '血',
    },
    tabs: { skills: '修炼', craft: '炼制', combat: '斗法', bag: '乾坤袋', shop: '坊市', rebirth: '转生', talents: '道韵', dungeon: '秘境', achievements: '成就' },
    side: { title: '修行录' },
    stats: { labels: { atk: { label: '攻' }, crit: { label: '暴', percent: true } } },
    units: {
      level: '{v} 层',
      seconds: '{v} 秒',
      minute: '{m} 分',
      hourMinute: '{h} 时 {m} 分',
    },
    icons: { buff: '丹', gear: '器', unknown: '？' },
    common: { needLevel: '需 {level} 层', needDaoYun: '需 {daoYun} 道韵', compareWrap: '（{compare}）', itemListSep: '、' },
    events: {
      lootGear: '妖物遗落【{name}】',
      lootGearLog: '夺得【{name}】',
      lootShowcase: '天降异宝！【{name}】',
      lootByproduct: '偶得 {name}×{count}',
      lootDrop: '得 {name}×{count}',
      lootCraft: '炼得 {name}×{count}',
      victoryFlog: '【{name}】轰然倒地！{summary}{compare}',
      victoryLog: '击倒【{name}】：{summary}{compare}',
      defeatFlog: '你不敌【{name}】',
      defeatToast: '斗法落败',
      eatHeal: '服下【{name}】，回气 {healed} 点',
      eatBuffToast: '服下【{name}】',
      eatBuffLog: '服下【{name}】，药力{minutes}分',
      equipWearToast: '已佩【{name}】',
      equipWearLog: '佩上【{name}】',
      equipRemoveLog: '卸下【{name}】',
      expCombat: '斗法修为 +{amount}',
      levelupToast: '升至 {level} 层',
      levelupLog: '【{name}】升至 {level} 层',
      sellLog: '卖出 {name}，得 {gained} 灵石',
      buyLog: '购入 {name}×{count}',
      rejectFallback: '此路不通',
      offlineToast: '离线 {away}归来',
      offlineLog: '离线修行 {away}：{items}{exp}',
      offlineNoYield: '无所获',
      offlineExpSuffix: '，修为 +{exp}',
      craftFail: '「{name}」炼制失败，材料尽失，仅悟得 {exp} 修为',
      craftHalt: '「{name}」材料告罄，熄炉中止',
      rebirthToast: '兵解功成，得 {daoYun} 道韵',
      rebirthLog: '兵解重修：{xp} 修为，{daoYun} 道韵（第 {count} 世）',
      talentBuyToast: '点亮【{name}】（{cost} 道韵）',
      talentBuyLog: '点亮【{name}】，余 {daoYun} 道韵',
      dungeonEnter: '踏入【{name}】第 {floor}/{floors} 层',
      dungeonFloor: '第 {floor}/{floors} 层已通：+{gold} 灵石 {items}',
      dungeonDaoYun: '，道韵 +{daoYun}',
      dungeonClear: '【{name}】已通关（{floors} 层）！',
      dungeonLeave: '退出【{name}】（第 {floor} 层，最深 {best}）',
      bossPhase: '【{enemy}】显露「{name}」之相！（阶段 {phase}）',
      achievementToast: '成就达成【{name}】',
      achievementLog: '成就达成【{name}】',
      gearSmelt: '熔炼【{name}】，得 {shard}×{count}',
      gearReforge: '重铸【{name}】，铭纹升至 T{tier}',
    },
    pages: {
      skills: {
        empty: '无可修技艺',
        chipLocked: '未开放',
        expSub: '修为 {into}/{need}',
        expMax: '修为已满',
        actNow: '当前 · {name}',
        idle: '未修行',
        stopBtn: '收功',
        running: '进行中',
        byproduct: '偶得 {name}',
        actMeta: '{interval} / 次',
        startBtn: '开始',
        realmLine: '境界 · {realm} · {rebirths} 世',
      },
      combat: {
        title: '斗法',
        subtitle: '当前斗法 {level} 层',
        enemyMissing: '妖物不知所踪',
        resting: '休整中',
        enemyHp: '敌 {ehp}/{hp}',
        selfStats: '己方 {hp}/{max}',
        fleeBtn: '撤退',
        autoFightOn: '自动再战 · 开',
        autoFightOff: '自动再战 · 关',
        autoEatOn: '自动嗑丹 · 开',
        autoEatOff: '自动嗑丹 · 关',
        noConsumables: '囊中无丹',
        enemyStats: '气血 {hp}',
        enemyGold: '灵石 {min}~{max}',
        dropsSuffix: ' · 掉落 {drops}',
        fightBtn: '挑战',
      },
      bag: {
        title: '乾坤袋',
        matGroup: '材料',
        consumableGroup: '丹药',
        priceEach: '每件 {price} 灵石',
        sellOneBtn: '卖一',
        sellAllBtn: '全卖',
        gearWorn: '佩戴中',
        gearLoose: '囊中',
        emptyWorn: '未佩戴',
        emptyLoose: '囊中无物',
        emptyAll: '空空如也',
        noAffix: '无属性',
        wearBtn: '佩戴',
        takeOffBtn: '卸下',
        sellBtn: '卖出',
        smeltBtn: '熔炼',
        reforgeBtn: '重铸',
        inscTier: 'T{tier}',
        inscCondition: '（受{element}）',
      },
      craft: {
        title: '炼制',
        subtitle: '丹器之道，当前 {level} 层',
        empty: '无可炼配方',
        expSub: '修为 {into}/{need}',
        expMax: '修为已满',
        actNow: '开炉 · {name}',
        idle: '未开炉',
        stopBtn: '熄炉',
        running: '炼制中',
        startBtn: '开炉',
        successRate: '成功率 {rate}%',
        matRow: '{name} {have}/{need}',
        recipeMeta: '{interval} / 炉 · 修为 +{exp}',
      },
      shop: { title: '坊市', subtitle: '以灵石易物', price: '{price} 灵石', owned: '持有 {count}', buyBtn: '买一' },
      rebirth: {
        title: '转生',
        subtitle: '第 {rebirths} 世',
        empty: '无兵解之法',
        xpLine: '总修为 {xp}',
        gainLine: '可得 {daoYun} 道韵',
        gateLine: '需 {need} 修为',
        resetTitle: '将散去',
        keepTitle: '将长存',
        performBtn: '兵解',
        confirmTip: '不可逆',
        confirmBtn: '确认',
        cancelBtn: '取消',
        resetLabels: { skills: '修为', items: '材料', gold: '灵石', buffs: '药力', lastEncounter: '旧账' },
        keepLabels: { gear: '法宝' },
      },
      talents: {
        title: '道韵天赋',
        subtitle: '现有 {daoYun} 道韵',
        empty: '无天赋',
        costRow: '耗 {cost}',
        needDaoYun: '道韵不足（需 {cost}）',
        needPrereq: '前置未成',
        owned: '已点亮',
        buyBtn: '点亮',
      },
      dungeon: {
        title: '秘境',
        subtitle: '层表驱动，逐层推进',
        empty: '无秘境',
        floorNow: '当前 · 第 {floor}/{floors} 层',
        best: '最深 · 第 {best} 层',
        powerNow: '战力 {power}',
        powerRec: '推荐 {min}~{max}',
        enterBtn: '进入',
        retreatBtn: '撤退',
        entryKey: '需 {item} ×1',
        clearBadge: '已通关',
      },
      achievements: {
        title: '成就',
        subtitle: '已解锁 {unlocked}/{total}',
        empty: '无成就',
        statsTitle: '修行统计',
        statLabels: { kills: '击杀', deaths: '败绩', rebirths: '兵解', cycles: '劳作', dungeonFloorBest: '最深秘境', maxHit: '最大一击', fastestKill: '最快击杀' },
        hiddenName: '？？？',
        hiddenDesc: '隐藏成就，达成后揭晓',
        unlockedBadge: '已达成',
        progress: '{current}/{target}',
        rewardGold: '灵石 +{gold}',
        rewardDaoYun: '道韵 +{daoYun}',
        rewardItems: '{items}',
      },
    },
  };
}

/**
 * 最小合法内容包（#7/#8 语义校验测试共享）：战斗+炼制双技能、一配方
 * （recipes minItems）、双敌人、全键 shell。测试用例在深拷贝上做单点
 * 破坏断言（结构关卡），语义正确性由修仙/魔幻包装配用例承载。
 */
export function minimalPack(): Record<string, unknown> {
  return {
    skills: [
      { id: 'fight', name: '斗法', icon: '斗', kind: 'combat' },
      { id: 'smith', name: '炼器', icon: '器', kind: 'craft' },
    ],
    items: [
      { id: 'herb1', name: '青灵草', icon: '青', type: 'mat', sell: 4 },
      { id: 'key1', name: '钥符', icon: '钥', type: 'mat', sell: 5 },
    ],
    recipes: [
      {
        name: '锻钥符',
        skill: 'smith',
        unlockLevel: 1,
        output: { item: 'key1', count: 1 },
        materials: { herb1: 2 },
        successRate: 1,
        interval: 4000,
        exp: 10,
      },
    ],
    enemies: [
      {
        id: 'e1', name: '青鬃狼', icon: '狼', level: 1, kind: 'claw',
        hp: 60, atk: 9, def: 2, attackInterval: 2800, exp: 16,
        gold: { min: 4, max: 10 }, drops: [],
      },
      {
        id: 'e2', name: '赤尾妖蝎', icon: '蝎', level: 8, kind: 'claw',
        hp: 140, atk: 17, def: 6, attackInterval: 2600, exp: 40,
        gold: { min: 12, max: 24 }, drops: [],
      },
    ],
    gearDrops: [],
    elements: [],
    rarities: [
      { id: 'common', name: '寻常', weight: 70, mult: 1, affix: 0, sell: 1 },
      { id: 'fine', name: '精良', weight: 20, mult: 1.15, affix: 1, sell: 2 },
      { id: 'rare', name: '罕见', weight: 8, mult: 1.3, affix: 2, sell: 4 },
      { id: 'epic', name: '绝世', weight: 2, mult: 1.5, affix: 3, sell: 10, showcase: true },
    ],
    affixPool: [
      { name: '锐锋', stat: 'atk', scale: 0.3 },
      { name: '罡气', stat: 'def', scale: 0.3 },
      { name: '浑厚', stat: 'hp', scale: 1.5 },
      { name: '通明', stat: 'crit', scale: 0.25 },
    ],
    combatText: {
      verbs: {
        basic: [{ v: '击', limbs: ['面门'] }],
        claw: [{ v: '抓', limbs: ['肩头'] }],
      },
      moves: { basic: ['搏兔一击'], e1: ['饿虎扑食'], e2: ['毒尾横扫'] },
      openings: ['你足尖一点'],
      critIntro: ['你气机鼓荡'],
      cons: {
        hit: {
          light: ['{defender}受创{d}点。'],
          mid: ['{defender}受创{d}点。'],
          heavy: ['{defender}受创{d}点。'],
          deadly: ['{defender}受创{d}点。'],
        },
        hurt: {
          light: ['你受创{d}点。'],
          mid: ['你受创{d}点。'],
          heavy: ['你受创{d}点。'],
          deadly: ['你受创{d}点。'],
        },
      },
      fatal: { hit: '{defender}受创{d}点！', hurt: '你受创{d}点。' },
      templates: {
        playerLight: ['你一招「{move}」，{weapon}{verb}向{defender}的{limb}。'],
        playerHeavy: ['{opening}——一招「{move}」，{weapon}{verb}向{defender}的{limb}。'],
        playerCrit: ['{critIntro}——「{move}」，{weapon}{verb}向{defender}的{limb}！'],
        enemyLight: ['{enemy}一式「{move}」，{verb}向你的{limb}。'],
        enemyHeavy: ['{enemy}凶性大发——「{move}」，{verb}向你的{limb}！'],
      },
      notes: {
        retreat: ['你收势撤战'],
        retreatToGather: ['你收势离战'],
        retreatWounded: ['你暂且退避'],
        retreatVictory: ['你见好就收'],
        reengage: ['你再度向【{enemy}】出手'],
        start: ['你与【{enemy}】战至一处'],
        autoConsume: ['你服下【{item}】'],
      },
      summary: {
        tiers: {
          light: ['轻痕积胜'], mid: ['稳中求进'], heavy: ['重创连绵'], deadly: ['锋芒毕露'],
        },
        base: ['{rounds} 合击倒 · {flavor}'],
        crit: ['{rounds} 合击倒 · {flavor} · {crits} 会心'],
      },
      compare: {
        revenge: ['今 {rounds} 合雪耻'],
        faster: ['今 {rounds} 合胜'],
        slower: ['今 {rounds} 合方克'],
        even: ['与前番 {rounds} 合如一'],
      },
    },
    texts: {
      basicName: '拳脚',
      reject: { '*': { 'bad-payload': '指令无效' } },
      shell: shellFixture(),
    },
    shop: [{ item: 'herb1', price: 10 }],
  };
}
