#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/steamworks.local.env}"
RELEASE_UNPACKED="$REPO_ROOT/packages/app-desktop/release/win-unpacked"
PACK_JSON="$REPO_ROOT/packages/content/src/packs/xiuxian.json"

# Windows 可用路径（steamcmd / vdf 用）；非 Windows 环境回落原样。
# cygpath -m = 正斜杠混合路径：SteamPipe vdf 原生接受，免反斜杠转义地狱。
if command -v cygpath >/dev/null 2>&1; then
  WIN_UNPACKED="$(cygpath -m "$RELEASE_UNPACKED")"
else
  WIN_UNPACKED="$RELEASE_UNPACKED"
fi
VDF_CONTENT_ROOT="$WIN_UNPACKED"

TOTAL_STAGES=8

banner "问道长生 · Steamworks 上架向导"

# ── 阶段 1：steamcmd 就位 ─────────────────────────────────────────────────
stage "准备 steamcmd"
say "SteamPipe 上传工具 steamcmd 是 Valve 官方命令行，只需装一次。"
if ask STEAMCMD_EXE "steamcmd.exe 的完整路径（已装？）：" && [[ -n "$STEAMCMD_EXE" ]] && [[ -f "$STEAMCMD_EXE" ]]; then
  note "使用已配置的 steamcmd：$STEAMCMD_EXE"
else
  say "还没装。下载官方 zip 并解压到任意目录（如 D:\\tools\\steamcmd）："
  open_url "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip"
  open_url "https://developer.valvesoftware.com/wiki/SteamCMD"
  step "解压后，把 steamcmd.exe 的完整路径粘贴回来。"
  ask STEAMCMD_EXE "steamcmd.exe 完整路径："
  if [[ -z "$STEAMCMD_EXE" || ! -f "$STEAMCMD_EXE" ]]; then
    warn "路径暂时无效也没关系——装好后重跑本向导或手动执行收尾命令即可。"
    SKIPPED+=("steamcmd 路径校验")
  else
    write_env STEAMCMD_EXE "$STEAMCMD_EXE"
  fi
fi
note "首次运行 steamcmd 会自动更新；登录时的 Steam Guard 验证码在邮箱/手机上。"

# ── 阶段 2：合作伙伴账号办理（纯人工，无法代办） ────────────────────────────
stage "Steamworks 合作伙伴账号"
say "发布游戏需要 Steamworks 合作伙伴账号（一次性办理，Valve 审核需数天）。"
open_url "https://partner.steamgames.com/publisherSignup"
step "用你的 Steam 账号登录，选择 个人 / 公司 形式提交合作伙伴申请。"
step "填写公司与银行资料、完成税务表格（Tax interviews）、签署数字协议。"
pause "资料提交完成后按回车（审核可能要几天，期间其余阶段可先跳过重跑）。"
if confirm "审核已通过、能登录 partner.steamgames.com 了吗？"; then
  :
else
  warn "审核期间无法创建应用——先做阶段 1，其余等过审后重跑本向导。"
  SKIPPED+=("Steamworks 过审（重跑本向导继续）")
  finish
  exit 0
fi

# ── 阶段 3：创建应用 + AppID ──────────────────────────────────────────────
stage "创建应用（AppID）"
say "每款应用需支付一笔可回收的应用费（上架营收回收后退还）。"
open_url "https://partner.steamgames.com/apps"
step "点 Create your first application / 创建新应用，按提示支付应用费。"
step "创建完成后，AppID 显示在应用管理页地址与应用列表里（纯数字）。"
ask APPID "粘贴 AppID："
while [[ ! "$APPID" =~ ^[0-9]+$ ]]; do
  warn "AppID 应为纯数字。"
  ask APPID "再粘贴一次 AppID："
done
write_env APPID "$APPID"

# ── 阶段 4：成就配置（API 名 = content 包成就 id，零映射） ────────────────
stage "成就配置"
say "本项目约定：content 包成就 id 就是 Steam 成就 API 名（无需映射表）。"
say "当前修仙包的成就 id 清单："
if command -v node >/dev/null 2>&1; then
  node -e "const p=require(process.argv[1]);(p.achievements||[]).forEach(a=>console.log('   · '+a.id))" "$PACK_JSON" ||
    warn "成就清单读取失败，请手动从 packages/content/src/packs/xiuxian.json achievements 节抄 id。"
else
  warn "未找到 node——成就 id 请看 packages/content/src/packs/xiuxian.json 的 achievements 节。"
fi
step "回 partner 站 → 你的应用 → Technical Tools → Achievements。"
step "逐条 Add achievement：API Name 填上面的 id；显示名/描述/图标可先占位后补。"
open_url "https://partner.steamgames.com/apps"
pause "全部成就建完后按回车。"

# ── 阶段 5：DepotID 与构建脚本生成 ────────────────────────────────────────
stage "生成 SteamPipe 构建脚本"
say "创建应用后 Steamworks 已自动建好主 depot，ID 在应用管理页 → depots。"
open_url "https://partner.steamgames.com/apps"
step "记下主 depot 的数字 ID（DepotID）。"
ask DEPOTID "粘贴 DepotID："
while [[ ! "$DEPOTID" =~ ^[0-9]+$ ]]; do
  warn "DepotID 应为纯数字。"
  ask DEPOTID "再粘贴一次 DepotID："
done
write_env DEPOTID "$DEPOTID"

APP_BUILD_VDF="$SCRIPT_DIR/app_build_${APPID}.vdf"
DEPOT_BUILD_VDF="$SCRIPT_DIR/depot_build_${DEPOTID}.vdf"
if [[ -f "$APP_BUILD_VDF" ]] && ! confirm "$APP_BUILD_VDF 已存在，覆盖？"; then
  note "保留现有构建脚本。"
else
  sed -e "s/<<APPID>>/${APPID}/g" \
      -e "s/<<DEPOTID>>/${DEPOTID}/g" \
      -e "s|<<CONTENT_ROOT>>|${VDF_CONTENT_ROOT}|g" \
      "$SCRIPT_DIR/app_build_TEMPLATE.vdf" > "$APP_BUILD_VDF"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$APP_BUILD_VDF"
fi
if [[ -f "$DEPOT_BUILD_VDF" ]] && ! confirm "$DEPOT_BUILD_VDF 已存在，覆盖？"; then
  note "保留现有 depot 脚本。"
else
  sed -e "s/<<DEPOTID>>/${DEPOTID}/g" \
      "$SCRIPT_DIR/depot_build_TEMPLATE.vdf" > "$DEPOT_BUILD_VDF"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$DEPOT_BUILD_VDF"
fi
note "contentroot 已指向：$WIN_UNPACKED"
note "换机/挪动仓库后 contentroot 会失效——重跑本阶段即可再生成。"

# ── 阶段 6：本地构建安装包 ────────────────────────────────────────────────
stage "本地构建（npm run dist）"
say "上传前需要最新打包产物（release/win-unpacked 即 depot 内容根）。"
if confirm "现在在仓库根跑 npm run dist 吗？（约几分钟；已构建过可选否）"; then
  (cd "$REPO_ROOT" && npm run dist)
else
  note "跳过构建——请确认此前构建产物仍然可用。"
fi

# ── 阶段 7：首次上传 ──────────────────────────────────────────────────────
stage "首次上传（steamcmd）"
say "构建器账号就是用于上传的 Steam 账号（首次可用自己的；密码由 steamcmd 交互输入，不经本脚本）。"
ask BUILDER_ACCOUNT "构建器 Steam 账号名："
write_env BUILDER_ACCOUNT "$BUILDER_ACCOUNT"
note "将执行：steamcmd +login <账号> +run_app_build <app_build vdf> +quit"
note "首次上传进 dev 分支，不会直接对玩家可见。"
if confirm "现在开始上传吗？（需 steamcmd 就位 + Steam Guard 验证码）"; then
  if [[ -z "$STEAMCMD_EXE" || ! -f "$STEAMCMD_EXE" ]]; then
    warn "steamcmd 路径无效，无法上传。"
    SKIPPED+=("首次上传（先补阶段 1 的 steamcmd 路径，再重跑本向导）")
  else
    VDF_WINPATH="$APP_BUILD_VDF"
    command -v cygpath >/dev/null 2>&1 && VDF_WINPATH="$(cygpath -m "$APP_BUILD_VDF")"
    "$STEAMCMD_EXE" +login "$BUILDER_ACCOUNT" +run_app_build "$VDF_WINPATH" +quit
  fi
else
  SKIPPED+=("首次上传（手动：steamcmd +login <账号> +run_app_build $APP_BUILD_VDF +quit）")
fi

# ── 阶段 8：发布与开发桥 ──────────────────────────────────────────────────
stage "Set live 与本机 Steam 模式"
open_url "https://partner.steamgames.com/apps"
step "上传成功后：应用管理页 → SteamPipe → Builds，把新构建 Set live。"
say "本机开发调试：无 STEAM_APPID 环境变量时壳走 mock 模式；"
say "想让打包版连真实 Steam 后端，可在 win-unpacked 放 steam_appid.txt（仅限本机调试）。"
if confirm "把 steam_appid.txt 写进 win-unpacked（本机调试用）？"; then
  printf '%s' "$APPID" > "$RELEASE_UNPACKED/steam_appid.txt"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$RELEASE_UNPACKED/steam_appid.txt"
  note "放心：depot 构建脚本已把 steam_appid.txt 排除，不会随包上传。"
else
  note "跳过——需要时手动创建。"
fi
say "商店页（价格/截图/介绍）不在本票范围，见 partner 站 Store 资产清单。"

finish
